### ISSUE TITLE
[BUG](Fedora 32) system-config-keyboard does not exist

### ISSUE THREAD

**Issue by DiscordiAnon** [Zer0CoolX/Fedora-KDE-Minimal-Install-Guide#10]
**system-config-keyboard** doesn't seem to exist on Fedora 32 and causes the bash script to exit.
Has the package been renamed or dropped completely?

**Comment by Zer0CoolX** [comment]
Honestly not sure. I have not had time to try this out with Fedora 32 yet. I may be able to give it a try in the next few days or this weekend and then update things.

In the meantime, feel free to: try without the package, research if the package has been changed/deprecated/replaced, etc.

Thanks

**Comment by DiscordiAnon** [comment]
I tried without the package and it installed fine. Been using it F32 for about a week now and everything works great.

**Comment by Zer0CoolX** [comment]
Sounds good, glad to hear its working. I didn't have time to try it before, possibly try it this weekend and do a little research on it. Thanks
