### ISSUE TITLE
Installing minimal KDE on existing Fedora 32

### ISSUE THREAD

**Issue by HuM4NoiD** [Zer0CoolX/Fedora-KDE-Minimal-Install-Guide#11]
I have already installed Fedora 32 with Gnome, I want to just try out the Desktop Environment without any of its applications like Okular or even essential ones like Kate or Konsole. I just want to get the feel of the DE, not of the apps. What packages should I follow or what modifications to the install script will do?

**Comment by Zer0CoolX** [comment]
I am sorry that is beyond the scope of this guide. I have never installed KDE in this capacity over an existing install/DE. It would be up to you to research the matter and/or try installing some/all of the packages from this guide. I would recommend testing in a VM before doing this on your main system. Good luck.
