### ISSUE TITLE
Several unnecessary packages can be removed or substituted from your installation instructions for Fedora 32 and up

### ISSUE THREAD

**Issue by ghost** [Zer0CoolX/Fedora-KDE-Minimal-Install-Guide#12]
adwaita-gtk2-theme: can be substituted for breeze-gtk for better intergration between qt and GTK out of the box.

firewall-config: unnecessary, should be removed.

kinfocenter: is broken on Fedora and is not required, it should be removed.

system-config-language & system-config-keyboard: one package is missing from the Fedora 32 repos, they are not required for a successful install, should be removed.

**Comment by Zer0CoolX** [comment]
Thanks for the info. I have not had much time (if any really) to update the script and test it with Fedora 32 myself. I am debating if I can keep it up to date or if I need to abandon this.

Depending on what I decide, I may make the suggested changes and test it. Either way appreciate the input.

**Comment by PsiACE** [comment]
@Zer0CoolX Thank you very much for your project, I just tested it on my own Fedora32, we can delete or replace unnecessary packages mentioned by @roesz

**Comment by Zer0CoolX** [comment]
@roesz If you would like to make the changes and submit the pull request I can approve the merge, this way you get credit for contributing. I will wait a little bit and if you dont do it I will do it for you. Thanks

@PsiACE Thank you for testing, I will either accept @roesz merge or update it myself.

**Comment by Zer0CoolX** [comment]
As no pull request was submitted I will make the changes myself. Thank you both for the help.
