### ISSUE TITLE
Install via short url and git tagged script for each Fedora release

### ISSUE THREAD

**Issue by RobbiNespu** [Zer0CoolX/Fedora-KDE-Minimal-Install-Guide#13]
Hello Zer0CoolX (nice nick),
First of all, thank for this guide lines. I have 2 suggestion
1) Add another "Tips" to download your script via short url 
which can be manage using curl command like this 
```bash
$ curl -L -o fedora-kde-min-packages.sh  https://git.io/JU9DV 
$ chmod a+x fedora-kde-min-packages.sh
$ sudo ./fedora-kde-min-packages.sh
```
if you are okey, i can send PR for this

2) Does it better to git tag which script on what fedora version? IMHO, not everyone want to use newer released version on first month. so maybe he/she prefer to use slightly 1 version older and update to recent version when 2-3 month after that (which is quite stable after a couple of period after newer fedora released).

**Comment by Zer0CoolX** [comment]
Thanks for the feedback.

While I understand the appeal of a shorter URL, I also strongly dislike (as do many security focused people) using shortened URL's as they mask the true destination of a link to less savvy users. This is especially true in the above context when its being used to get a script via the terminal.

If the drive behind a shorter URL is for when its not possible to copy/paste then I would think each individual can simply use whatever URL shortener they like, shorten the official link and type in it themselves so they are 100% in control of the process. If I am missing some other motivation for a short URL let me know.

As for the second part I certainly understand that this would provide more choice to a wider range of people. However I do not really have the time/ability to maintain multiple versions of the process. In all honesty its something I worked out for my own personal needs and decided to share it with others.

Currently I have not even really kept up with the guide myself. As time goes on it may end up being something I no longer update.

I think it would be better for people to fork it and maintain it as they see fit for their personal needs. For example you might consider forking it and making the changes you recommend. I would have no issue with you posting a link to your forked version with those changes as a reply in this issue.
