### ISSUE TITLE
Remove Qt4 dependencies

### ISSUE THREAD

**Issue by KAMiKAZOW** [Zer0CoolX/Fedora-KDE-Minimal-Install-Guide#2]
kdelibs, kde-runtime, kde-platform-plugin, and phonon-backend-gstreamer are definitively Qt4-based. Plasma 5 runs fine without Qt4.

**Comment by Zer0CoolX** [comment]
Thanks for the heads up. I will do some testing to see if removing them leads to any issues, if not I will remove them from the directions and script

**Comment by KAMiKAZOW** [comment]
I did not check the entire dependency tree whether something will still pull Qt4 or not. Those four packages just jumped into my eye.

**Comment by Zer0CoolX** [comment]
I am spinning up a VM now to test this out. If you spot anything more let me know. I would like to "trim the fat" from this as much as possible so this input is very helpful. Thanks.

**Comment by KAMiKAZOW** [comment]
As I wrote in #1: Contrary to your comment there kcolorchooser is being explicitly installed by your script.

**Comment by Zer0CoolX** [comment]
Thanks for pointing that out, I will remove it prior to testing. I must have overlooked that

**Comment by Zer0CoolX** [comment]
I noticed qt5-qdebugviewer also gets installed as a weak dependency but cant figure out by which package. Any ideas on figuring out whats installing it?

Otherwise so far I have removed the packages we discussed and it appears to work. I will do a little more poking at it prior to committing the changes.

Thanks

**Comment by Zer0CoolX** [comment]
As Fedora 30 just released and I am having trouble getting it working in ESXi 6.7 U1 (worked fine on a laptop) I am going to close this for now as I am re-evaluating what packages are required for this to work anyhow. Not sure yet if its an ESXi related issue or an issue with my process. I will merge the changes into main branch
