### ISSUE TITLE
Why use Akonadi? is that required?

### ISSUE THREAD

**Issue by ekocahyo** [Zer0CoolX/Fedora-KDE-Minimal-Install-Guide#9]
after I read this references:
https://userbase.kde.org/Akonadi
I think akonadi is not needed

**Comment by Zer0CoolX** [comment]
I had a conversation with someone on the topic a while back. Please feel free to [read over it](https://www.reddit.com/r/Fedora/comments/bn173n/fedora_30_kde_minimal_install_guidescript/erh19ol?utm_source=share&utm_medium=web2x) and see if you agree with the stance on it. You can certainly remove it yourself before running the script or applying the steps manually but I think the end determination was it would provide value to the majority using my method/script.

If you want to continue that conversation best to do so here and not on reddit as the thread is old there.
